name: Run shunit2 tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install necessary packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y exiftool ffmpeg jq libid3-tools shunit2

      - name: Run shunit2 tests
        run: |
          for test_script in test/test-*.sh; do
            bash "${test_script}"
          done
          echo "Passed!"
          exit 0
